CREATE TABLE IF NOT EXISTS `tb_pedido` (
   `id` bigint(20) NOT NULL AUTO_INCREMENT,
   `titulo` varchar(150) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
